### ISSUE TITLE
Set Kinematic Dynamic Rigid Bodies to Not Update with Parent Transform Changes by Default

### ISSUE THREAD

**Issue by TheOneAbis** [o3de/rfcs#51]
### Summary:

This RFC proposes a change to how dynamic rigid bodies react to parent transform changes at runtime, specifically their default setting for whether to ignore changes or not. Rigid bodies in SIMULATED mode will not be changed, but bodies set to KINEMATIC mode in the editor should by default listen to parent transform changes.

### What is the motivation for this suggestion?

This makes more sense intuitively since kinematic rigid bodies by definition have their translations and rotations specifically altered via direct changes to those transforms programmatically. In other words, if simulated bodies should be altered via the physics world only, then kinematic bodies should be altered only via anything else, whether it be scripted behavior or behavior resulting from the parent transform.

One common use case for this, in the context of games, would be to be able to add trigger colliders to entities that are children of a parent, which developers would want for things like being able to interact in some way with only a specific section of an object, i.e. a "weak spot" on an enemy that can be shot at.

Another example, one that would benefit me individually, would be adding an "interaction" sphere in front of the player so that anything that overlaps that sphere can be interacted with.

The ideal outcome for this is a more accurate understanding of kinematic vs simulated dynamic RB's, intuitively, as well as being able to add different collider shapes to child entities that make up parts of an object and have them actually move around as those parts would.

### What are the advantages of the suggestion?
- Being able to have colliders on children react to parent transform data without needing to explicitly tell them t do so via the transform interface.

### What are the disadvantages of the suggestion?
- It is possible that projects that were previously relying on the current default setting for kinematic rigid bodies may no longer work properly.

### How will this be work within the O3DE project?

If a rigid body is set to simulated in the editor, it will not react to parent changes at runtime.
If a rigid body is set to kinematic in the editor, it will react to parent changes at runtime.
There should be no differences with setting a rigid body to kinematic at runtime as compared to how it already works currently, since TransformBus::SetOnParentChangedBehavior already does not apply to simulated bodies anyway.

### Are there any alternatives to this suggestion?

The only alternative would be to manually set on parent transform changed behavior programmatically for every entity the user intends to have changed by the parent. This can get tedious quickly, and while this would setill need to happen for the other way around if we made this change, I think it would be used less because having kinematic bodies react to parent changes is the more intuitive behavior.
### What is the strategy for adoption?

- This change should be invisible to most users; if they want it to act the way it used to, they'd have to use the transform interface as described above, which is already an existing feature.
- It also shouldn't need to be taught, as ideally it's the more expected behavior to begin with.

**Comment by michalpelka** [comment]
This RFC proposes changes to the behavior of kinematic actors in PhysX.
I understand there is a problem with interacting with the kinematic rigid body, but I disagree that the mechanism currently exists. 
Currently, there is no difference in simulated rigid bodies in o3de: those follow the transforms produced by PhysX. 

With kinematic bodies, there are [two APIs](https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/RigidBodyDynamics.html#kinematic-surface-velocities) that allow to change the position of such body in the world.
- `PxRigidDynamic::setKinematicTarget()` 
Allows to move the body to a new location with infinite force, resolving all collisions.
- `PxRigidActor::setGlobalPose()`
Allows to teleport the body to a new position.

The first problem is API here - which is better for your use case (and other users').
The next step is the problem of the physics sampling.
The o3de **TransformBus** works with the framerate of the application, but PhysX usually works often (a few times faster). For one frame, the physics scene is updated multiple times. kinematic bodies should be updated in every tick. Without that, in the first PhysX tick, the body will be kinematically moved to a new position, but for the next tick will be stationary. That can cause instability in contacts that were created. 

On another hand currently, the only way to affect the position of the kinematic body is by using ebus : 
```Physics::RigidBodyRequests::SetKinematicTarget```.
I would rather propose adding a custom component that allows us to set a kinematic target from the parent's transform - that would solve your primary case, but still won't be the ideal solution regarding physics sampling.

Another option to evaluate is to use scene queries instead of trigger colliders. The difference is that it needs no rigid bodies.
Please adjust RFC taking into consideration the limitations and problems that I described.

**Comment by adamdbrw** [comment]
@TheOneAbis @michalpelka I propose to get all the comments to the RFC by the end of the month (30th Nov).

**Comment by michalpelka** [comment]
Discussed on sig-simulation issue triage. There are no comments from any party, so it was decided to close this RFC, without further action.
